/*
 * Pushserver API
 * HTTP API for the open pushserver implementation.
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.bubu1.pushclient.apimodels;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Data for registering a new App
 */
@ApiModel(description = "Data for registering a new App")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-08-09T15:35:25.389+02:00[Europe/Berlin]")
public class AppRegistration {
  public static final String SERIALIZED_NAME_REGISTRATION_ID = "registration_id";
  @SerializedName(SERIALIZED_NAME_REGISTRATION_ID)
  private String registrationId;

  public AppRegistration registrationId(String registrationId) {
    this.registrationId = registrationId;
    return this;
  }

   /**
   * Token with which the pushclient can identify the target application, so it doesn&#39;t have to store routing token.
   * @return registrationId
  **/
  @ApiModelProperty(example = "XXAAj76gkjlsfdhalSKL", required = true, value = "Token with which the pushclient can identify the target application, so it doesn't have to store routing token.")
  public String getRegistrationId() {
    return registrationId;
  }

  public void setRegistrationId(String registrationId) {
    this.registrationId = registrationId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppRegistration appRegistration = (AppRegistration) o;
    return Objects.equals(this.registrationId, appRegistration.registrationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(registrationId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppRegistration {\n");
    sb.append("    registrationId: ").append(toIndentedString(registrationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

