/*
 * Pushserver API
 * HTTP API for the open pushserver implementation.
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.bubu1.pushclient.apimodels;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Message
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-23T17:14:54.483+01:00[Europe/Berlin]")
public class Message {
  public static final String SERIALIZED_NAME_TOKEN = "token";
  @SerializedName(SERIALIZED_NAME_TOKEN)
  private String token;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private Map<String, Object> data = new HashMap<>();

  /**
   * (currently unused)
   */
  @JsonAdapter(PriorityEnum.Adapter.class)
  public enum PriorityEnum {
    NORMAL("normal"),
    
    HIGH("high");

    private String value;

    PriorityEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PriorityEnum fromValue(String value) {
      for (PriorityEnum b : PriorityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<PriorityEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PriorityEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PriorityEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return PriorityEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_PRIORITY = "priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  private PriorityEnum priority;

  public static final String SERIALIZED_NAME_TIME_TO_LIVE = "time_to_live";
  @SerializedName(SERIALIZED_NAME_TIME_TO_LIVE)
  private Integer timeToLive;

  public static final String SERIALIZED_NAME_COLLAPSE_KEY = "collapse_key";
  @SerializedName(SERIALIZED_NAME_COLLAPSE_KEY)
  private String collapseKey;


  public Message token(String token) {
    
    this.token = token;
    return this;
  }

   /**
   * Token to target a mobile application.
   * @return token
  **/
  @ApiModelProperty(example = "8904j76gkjlsfdhalSKL", required = true, value = "Token to target a mobile application.")

  public String getToken() {
    return token;
  }


  public void setToken(String token) {
    this.token = token;
  }


  public Message data(Map<String, Object> data) {
    
    this.data = data;
    return this;
  }

  public Message putDataItem(String key, Object dataItem) {
    this.data.put(key, dataItem);
    return this;
  }

   /**
   * Key value pairs to be delivered to the targeted application.
   * @return data
  **/
  @ApiModelProperty(example = "{\"title\":\"New Message\",\"body\":\"You got a new message!\",\"foo\":\"bar\"}", required = true, value = "Key value pairs to be delivered to the targeted application.")

  public Map<String, Object> getData() {
    return data;
  }


  public void setData(Map<String, Object> data) {
    this.data = data;
  }


  public Message priority(PriorityEnum priority) {
    
    this.priority = priority;
    return this;
  }

   /**
   * (currently unused)
   * @return priority
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "(currently unused)")

  public PriorityEnum getPriority() {
    return priority;
  }


  public void setPriority(PriorityEnum priority) {
    this.priority = priority;
  }


  public Message timeToLive(Integer timeToLive) {
    
    this.timeToLive = timeToLive;
    return this;
  }

   /**
   * (currently unused) How long to store the message (in seconds) for offline devices
   * @return timeToLive
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2419200", value = "(currently unused) How long to store the message (in seconds) for offline devices")

  public Integer getTimeToLive() {
    return timeToLive;
  }


  public void setTimeToLive(Integer timeToLive) {
    this.timeToLive = timeToLive;
  }


  public Message collapseKey(String collapseKey) {
    
    this.collapseKey = collapseKey;
    return this;
  }

   /**
   * (currently unused) Store only one message per collapse_key, set to something different to store multiple messages
   * @return collapseKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "(currently unused) Store only one message per collapse_key, set to something different to store multiple messages")

  public String getCollapseKey() {
    return collapseKey;
  }


  public void setCollapseKey(String collapseKey) {
    this.collapseKey = collapseKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Message message = (Message) o;
    return Objects.equals(this.token, message.token) &&
        Objects.equals(this.data, message.data) &&
        Objects.equals(this.priority, message.priority) &&
        Objects.equals(this.timeToLive, message.timeToLive) &&
        Objects.equals(this.collapseKey, message.collapseKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, data, priority, timeToLive, collapseKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Message {\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    timeToLive: ").append(toIndentedString(timeToLive)).append("\n");
    sb.append("    collapseKey: ").append(toIndentedString(collapseKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

